//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qr_genrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC_Tabel
    {
        public int DOC_ID { get; set; }
        public string DOC_MAIL { get; set; }
        public string DOC_PASSWORD { get; set; }
    }
}
